### ISSUE TITLE
请问没有注入声卡驱动 声卡可不可以正常使用

### ISSUE THREAD

**Issue by Hsintao** [ArchFeh/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI-factory#1]
RT

**Comment by ArchFeh** [comment]
如果你的音响麦克风要插音频输入接口的话就无法使用，如果你使用usb接口的耳机耳麦就不影响使用

**Comment by Hsintao** [comment]
> 如果你的音响麦克风要插音频输入接口的话就无法使用，如果你使用usb接口的耳机耳麦就不影响使用

哦哦 也就是音频输出是可以用的
